listen=YES
listen_ipv6=NO
background=YES

anonymous_enable=NO
local_enable=YES
write_enable=YES

local_umask=002
file_open_mode=0664

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/wired/data

dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
xferlog_std_format=YES
log_ftp_protocol=YES

ftpd_banner=The Wired FTP Server

userlist_enable=YES
userlist_deny=YES
userlist_file=/etc/vsftpd/user_list

user_config_dir=/etc/vsftpd/user_conf

pasv_enable=YES
pasv_address=10.72.2.2
pasv_min_port=30000
pasv_max_port=30010

seccomp_sandbox=NO
